#tomcat port
server:
  port: 9002
#jsp
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dahyeon.csrlk5yb8rrm.ap-northeast-2.rds.amazonaws.com:3306/webservice
    username: wjdek02
    password: jdh960530
#mybatis
mybatis:
  type-aliases-package: sist.data.*
  mapper-locations:
  - /mapper/**/*.xml